spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:example
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect

digitalchief:
  db:
    example:
      liquibase:
        enabled: true
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:example
        user: postgres
        password: postgres
